### ISSUE TITLE
TypeError: CustomTrainerForgetting.compute_loss() got an unexpected keyword argument 'num_items_in_batch'

### ISSUE THREAD

**Issue by liuyugeng** [sail-sg/closer-look-LLM-unlearning#1]
Hi, when I try to train the model, it returns the following error. 

```
Traceback (most recent call last):
  File "closer-look-LLM-unlearning/forget.py", line 245, in main
    trainer.train()
  File "anaconda3/envs/tofu/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "anaconda3/envs/tofu/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "anaconda3/envs/tofu/lib/python3.10/site-packages/transformers/trainer.py", line 3579, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
TypeError: CustomTrainerForgetting.compute_loss() got an unexpected keyword argument 'num_items_in_batch'
```

I just followed the instructions ```bash scripts/continual_tofu/idk_ap.sh```.

**Comment by liuyugeng** [comment]
I think in the [compute_loss](https://github.com/sail-sg/closer-look-LLM-unlearning/blob/9b4f1bcc5a782e88b392ceba9cdc6b681e0f7632/trainer/trainer.py#L24) function of trainer class, you should add ```num_items_in_batch=None```.

**Comment by LetheSec** [comment]
Thanks for your question.  This issue seems to be related to the version of the `transformers` library. You can try upgrading to the latest version to resolve this issue.

**Comment by liuyugeng** [comment]
I just upgraded to the latest library (4.46.3) and found this issue.

**Comment by LetheSec** [comment]
Oh, you're right. The version of `transformers` should be `<4.46`, and we used `4.43.0` in our experiments.
